Repository openshift-assisted/assisted-installer-app, pull requests merged in 2024-09, with the labels that each got.

#15 ci: Fix custom pipeline
  .tekton/assisted-installer-app-saas-main-pull-request.yaml
  .tekton/assisted-installer-app-saas-main-push.yaml
Labels: size/L

#17 ci: Fix main Konflux pipeline
  .tekton/assisted-installer-app-saas-main-push.yaml
Labels: size/L

#18 ci: Change image tag sha size
  build_deploy.sh
Labels: size/XS

#20 ci: Apply migration steps
  .tekton/assisted-installer-app-saas-main-pull-request.yaml
  .tekton/assisted-installer-app-saas-main-push.yaml
Labels: lgtm, size/M

#23 Update Assisted UI Lib to v2.34.2
  package-lock.json
  package.json
  yarn.lock
Labels: size/M
