Repository openshift-assisted/assisted-installer-app, pull requests merged in 2025-04, with the labels that each got.

#56 MGMT-20263: Solving problems formatting dates
  package-lock.json
  package.json
  src/i18n.ts
Labels: jira/valid-reference, size/M

#57 Update Assisted UI Lib to v2.38.5
  package-lock.json
  package.json
Labels: size/M

#59 Update Assisted UI Lib to 2.39.0
  package-lock.json
  package.json
Labels: size/M

#60 Revert "Update Assisted UI Lib to 2.39.0"
  package-lock.json
  package.json
Labels: size/M

#64 NO-ISSUE: Apply konflux migration
  .tekton/assisted-installer-app-saas-main-pull-request.yaml
  .tekton/assisted-installer-app-saas-main-push.yaml
Labels: jira/valid-reference, size/XS

#65 NO-ISSUE: Fix snyk task
  .tekton/assisted-installer-app-saas-main-pull-request.yaml
  .tekton/assisted-installer-app-saas-main-push.yaml
Labels: size/S, jira/valid-reference

#66 Update Assisted UI Lib to v2.39.2
  package-lock.json
  package.json
Labels: size/M

#69 Update Assisted UI Lib to v2.39.4
  package-lock.json
  package.json
Labels: size/M

#73 Update Assisted UI Lib to v2.40.0
  package-lock.json
  package.json
Labels: size/M
