Repository openshift-assisted/assisted-installer-app, pull requests merged in 2025-03, with the labels that each got.

#47 Changes related witht the decoupling
  fec.config.js
  package-lock.json
  package.json
  src/components/AssistedInstallerDetailCard.tsx
  src/components/RootApp.tsx
  yarn.lock
Labels: size/XXL

#48 Fix app init
  .gitignore
  src/components/AssistedInstallerDetailCard.tsx
  src/components/RootApp.tsx
  src/hooks/useInitApp.ts
  yarn.lock
Labels: size/XXL

#50 Fix stage/prod url retrieval logic
  src/components/AssistedInstallerDetailCard.tsx
  src/components/RootApp.tsx
  src/hooks/useInitApp.ts
Labels: size/M

#51 Adding HostsClusterDetailTab component
  src/components/HostsClusterDetailTab.tsx
Labels: size/S

#52 Ensure i18n is initialized in init hook
  src/components/AssistedInstallerDetailCard.tsx
  src/components/RootApp.tsx
  src/hooks/useInitApp.ts
Labels: size/XS

#54 Solving problems with scrollbar
  src/components/RootApp.tsx
Labels: size/S
